# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

self-hosted-runner:
  labels:
    - linux-amd64-cpu4
    - linux-arm64-cpu4
