#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import subprocess
import sys
import tarfile
import tomllib
import urllib.request
import zipfile
from email.parser import Parser
from pathlib import Path
from typing import Any, TypedDict, cast

ATTRIBUTIONS_MD_LICENSE_PREFIX = """<!--
SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
-->
"""

ROOT = Path(__file__).resolve().parents[2]
NODE = ROOT / "crates" / "node"


class RenderedPythonPackage(TypedDict):
    """Normalized Python package data ready to be rendered into markdown."""

    name: str
    version: str
    license_name: str
    license_texts: list[tuple[str, str]]


PYTHON_HEADER = f"""{ATTRIBUTIONS_MD_LICENSE_PREFIX}

# Third-Party Software Attributions (Python)

This project uses the following third-party Python packages.
Each package is open-source and licensed under the terms indicated below.

This file is automatically generated from **uv.lock**
Please do not edit it directly. Regenerate with `./scripts/generate_attributions.sh python`
"""

NODE_HEADER = f"""{ATTRIBUTIONS_MD_LICENSE_PREFIX}

# Third-Party Software Attributions (Node.js)

This project uses the following third-party npm packages for the Node.js bindings.
Each package is open-source and licensed under the terms indicated below.

This file is automatically generated from **package-lock.json**
Please do not edit it directly. Regenerate with `./scripts/generate_attributions.sh node`
"""


def spdx_url(license_field: str, *, fallback: str) -> str:
    """Map a simple SPDX-looking license string to an SPDX page, otherwise use a generic fallback."""
    s = license_field.strip()
    if not s or s == "UNKNOWN":
        return fallback
    m = re.match(r"^([A-Za-z0-9.\-]+)$", s)
    if m:
        return f"https://spdx.org/licenses/{m.group(1)}.html"
    if " OR " in s or " AND " in s or "(" in s:
        return "https://spdx.org/licenses/"
    return fallback


def _pypi_license_path_display(license_file: str) -> str:
    """Match Dynamo ATTRIBUTIONS-Python.md: paths like ``licenses/LICENSE`` under .dist-info."""
    if not license_file or license_file == "UNKNOWN":
        return "LICENSE"
    p = license_file.replace("\\", "/")
    for marker in (".dist-info/", ".egg-info/"):
        if marker in p:
            return p.split(marker, 1)[1]
    name = Path(p).name
    return name if name else "LICENSE"


def _relative_archive_path_display(path: str) -> str:
    """Drop the sdist root directory so rendered paths match the installed-package style."""
    p = path.replace("\\", "/")
    if "/" in p:
        return p.split("/", 1)[1]
    return p


def _md_inline_safe(s: str) -> str:
    """Wrap s in markdown inline code, using double-backtick delimiters if s contains a backtick."""
    if "`" in s:
        return f"`` {s} ``"
    return f"`{s}`"


def _normalize_package_name(name: str) -> str:
    """Normalize names per Python package matching rules so lockfile/install rows can be joined reliably."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _lockfile_registry_packages() -> dict[str, dict[str, Any]]:
    """Return {normalized_name: package_entry} for all third-party registry packages in uv.lock."""
    with open(ROOT / "uv.lock", "rb") as f:
        lock: dict[str, Any] = tomllib.load(f)
    return {
        _normalize_package_name(str(pkg["name"])): pkg
        for pkg in cast(list[dict[str, Any]], lock.get("package", []))
        if pkg.get("name") and pkg.get("version") and cast(dict[str, Any], pkg.get("source", {})).get("registry")
    }


def _render_python_package(
    parts: list[str], *, name: str, version: str, license_name: str, license_texts: list[tuple[str, str]]
) -> None:
    """Append one Python package section to the markdown output."""
    parts.append(f"## {name} ({version})\n\n")
    parts.append("### Licenses\n")
    parts.append(f"License: {_md_inline_safe(license_name)}\n\n")
    for path_label, text in license_texts:
        parts.append(f"  - {_md_inline_safe(path_label)}:\n")
        parts.append("```\n")
        parts.append(text if text.endswith("\n") else text + "\n")
        parts.append("```\n\n")


def _hash_matches(data: bytes, expected_hash: str) -> bool:
    """Validate an artifact against the hash recorded in uv.lock."""
    algo, _, value = expected_hash.partition(":")
    if algo != "sha256" or not value:
        raise ValueError(f"Unsupported hash format: {expected_hash}")
    return hashlib.sha256(data).hexdigest() == value


def _download_locked_artifact(url: str, expected_hash: str) -> bytes:
    """Download one locked artifact and fail closed if its hash does not match uv.lock."""
    with urllib.request.urlopen(url, timeout=10) as response:  # noqa: S310
        data = response.read()
    if not _hash_matches(data, expected_hash):
        raise ValueError(f"Hash mismatch for {url}")
    return data


def _metadata_license_classifiers(msg) -> list[str]:
    """Extract the license portion of Trove classifiers from parsed package metadata."""
    found: list[str] = []
    for classifier in msg.get_all("Classifier", []):
        if not classifier.startswith("License ::"):
            continue
        tail = classifier.split("::")[-1].strip()
        if tail and tail not in found:
            found.append(tail)
    return found


def _metadata_license_name(msg) -> str:
    """Choose the best human-readable license label from package metadata.

    Prefer modern SPDX-style fields, then legacy free-form license text, then
    Trove classifiers as the final fallback.
    """
    for field in ("License-Expression", "License"):
        value = (msg.get(field) or "").strip()
        value = " ".join(value.split())
        if value:
            if len(value) > 200:
                return "See package metadata"
            return value
    classifiers = _metadata_license_classifiers(msg)
    if classifiers:
        return " OR ".join(classifiers)
    return "UNKNOWN"


def _extract_zip_text(zf: zipfile.ZipFile, path: str) -> str | None:
    """Read a text file from a wheel, returning None when the path is absent."""
    try:
        return zf.read(path).decode("utf-8", errors="replace").strip()
    except KeyError:
        return None


def _extract_tar_text(tf: tarfile.TarFile, path: str) -> str | None:
    """Read a text file from an sdist, returning None when the path is absent."""
    try:
        member = tf.getmember(path)
    except KeyError:
        return None
    fileobj = tf.extractfile(member)
    if fileobj is None:
        return None
    return fileobj.read().decode("utf-8", errors="replace").strip()


def _common_license_candidates(paths: list[str]) -> list[str]:
    """Heuristic fallback for packages that ship license files without License-File metadata."""
    preferred = ("license", "licence", "copying", "notice", "authors")
    return [path for path in sorted(paths) if Path(path).name.lower().startswith(preferred)]


def _license_name_rank(path: str) -> int:
    """Rank more canonical license filenames ahead of generic notice-style files."""
    name = Path(path.replace("\\", "/")).name.lower()
    if name == "license":
        return 0
    if name.startswith("license."):
        return 1
    if "license" in name:
        return 2
    if name == "licence":
        return 3
    if name.startswith("licence."):
        return 4
    if "licence" in name:
        return 5
    if name == "copying":
        return 6
    if name.startswith("copying."):
        return 7
    if "copying" in name:
        return 8
    if name == "notice":
        return 9
    if name.startswith("notice."):
        return 10
    if "notice" in name:
        return 11
    if name == "authors":
        return 12
    if name.startswith("authors."):
        return 13
    if "authors" in name:
        return 14
    return 99


def _license_path_depth(path: str) -> int:
    """Count path nesting so package-level license files win over vendored subtree licenses."""
    normalized = path.replace("\\", "/").strip("/")
    return normalized.count("/") if normalized else 0


def _choose_declared_license(candidates: list[tuple[int, str, str, str]]) -> tuple[str, str] | None:
    """Choose one canonical declared License-File match.

    Candidates are ``(declared_index, relative_path, display_path, text)``.
    Only ``LICENSE``-style basenames participate so metadata does not pull in
    vendored subtree notices when a package-level license exists.
    """
    license_named = [
        candidate for candidate in candidates if "license" in Path(candidate[1].replace("\\", "/")).name.lower()
    ]
    if not license_named:
        return None
    _, _, display_path, text = min(
        license_named,
        key=lambda candidate: (_license_path_depth(candidate[1]), candidate[0], candidate[1].lower()),
    )
    return display_path, text


def _choose_heuristic_license(candidates: list[tuple[str, str, str]]) -> tuple[str, str] | None:
    """Choose one fallback license-like file when metadata is missing or unhelpful.

    Candidates are ``(relative_path, display_path, text)``.
    """
    if not candidates:
        return None
    _, display_path, text = min(
        candidates,
        key=lambda candidate: (
            _license_path_depth(candidate[0]),
            _license_name_rank(candidate[0]),
            candidate[0].lower(),
        ),
    )
    return display_path, text


def _declared_wheel_license_texts(
    zf: zipfile.ZipFile, dist_info_dir: str, declared_files: list[str]
) -> list[tuple[str, str]]:
    """Return the best declared wheel license file, if the wheel bundles one."""
    declared_candidates: list[tuple[int, str, str, str]] = []
    for declared_index, rel in enumerate(declared_files):
        candidates = [f"{dist_info_dir}/licenses/{rel}", f"{dist_info_dir}/{rel}"]
        for candidate in candidates:
            text = _extract_zip_text(zf, candidate)
            if text:
                declared_candidates.append(
                    (declared_index, rel, _pypi_license_path_display(candidate), text),
                )
                break
    selected_declared = _choose_declared_license(declared_candidates)
    return [selected_declared] if selected_declared else []


def _heuristic_wheel_license_texts(zf: zipfile.ZipFile, dist_info_dir: str) -> list[tuple[str, str]]:
    """Return a fallback wheel license file when metadata does not declare one."""
    heuristic_paths = _common_license_candidates(
        [
            name
            for name in zf.namelist()
            if name.startswith(f"{dist_info_dir}/licenses/") or name.startswith(f"{dist_info_dir}/")
        ]
    )
    heuristic_candidates: list[tuple[str, str, str]] = []
    for candidate in heuristic_paths:
        text = _extract_zip_text(zf, candidate)
        if text:
            display_path = _pypi_license_path_display(candidate)
            heuristic_candidates.append((display_path, display_path, text))
    selected_heuristic = _choose_heuristic_license(heuristic_candidates)
    return [selected_heuristic] if selected_heuristic else []


def _wheel_metadata_from_bytes(data: bytes, *, package_name: str) -> tuple[str, list[tuple[str, str]]]:
    """Extract a license label and bundled license texts from one wheel artifact."""
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        metadata_paths = [name for name in zf.namelist() if name.endswith(".dist-info/METADATA")]
        if not metadata_paths:
            raise ValueError(f"No METADATA found in wheel for {package_name}")
        metadata_path = metadata_paths[0]
        dist_info_dir = metadata_path.rsplit("/", 1)[0]
        metadata = Parser().parsestr(zf.read(metadata_path).decode("utf-8", errors="replace"))
        license_name = _metadata_license_name(metadata)
        license_texts = _declared_wheel_license_texts(zf, dist_info_dir, metadata.get_all("License-File", []))
        if not license_texts:
            # Older wheels often omit License-File entries but still bundle a LICENSE-like file.
            license_texts = _heuristic_wheel_license_texts(zf, dist_info_dir)
        return license_name, license_texts


def _declared_sdist_license_texts(
    tf: tarfile.TarFile, root_dir: str, declared_files: list[str]
) -> list[tuple[str, str]]:
    """Return the best declared sdist license file, if the sdist bundles one."""
    declared_candidates: list[tuple[int, str, str, str]] = []
    for declared_index, rel in enumerate(declared_files):
        candidate = f"{root_dir}/{rel}"
        text = _extract_tar_text(tf, candidate)
        if text:
            declared_candidates.append(
                (declared_index, rel, _relative_archive_path_display(candidate), text),
            )
    selected_declared = _choose_declared_license(declared_candidates)
    return [selected_declared] if selected_declared else []


def _heuristic_sdist_license_texts(tf: tarfile.TarFile, root_dir: str) -> list[tuple[str, str]]:
    """Return a fallback sdist license file when metadata does not declare one."""
    heuristic_paths = _common_license_candidates([name for name in tf.getnames() if name.startswith(f"{root_dir}/")])
    heuristic_candidates: list[tuple[str, str, str]] = []
    for candidate in heuristic_paths:
        text = _extract_tar_text(tf, candidate)
        if text:
            display_path = _relative_archive_path_display(candidate)
            heuristic_candidates.append((display_path, display_path, text))
    selected_heuristic = _choose_heuristic_license(heuristic_candidates)
    return [selected_heuristic] if selected_heuristic else []


def _sdist_metadata_from_bytes(data: bytes, *, package_name: str) -> tuple[str, list[tuple[str, str]]]:
    """Extract a license label and bundled license texts from one sdist artifact."""
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:*") as tf:
        members: list[str] = [name for name in tf.getnames() if name.endswith("/PKG-INFO")]
        if not members:
            raise ValueError(f"No PKG-INFO found in sdist for {package_name}")
        metadata_path = cast(str, min(members, key=len))
        root_dir = metadata_path.split("/", 1)[0]
        raw = _extract_tar_text(tf, metadata_path)
        if raw is None:
            raise ValueError(f"Failed to read PKG-INFO from sdist for {package_name}")
        metadata = Parser().parsestr(raw)
        license_name = _metadata_license_name(metadata)
        license_texts = _declared_sdist_license_texts(tf, root_dir, metadata.get_all("License-File", []))
        if not license_texts:
            # Sdists are our best fallback for unresolved packages because they are typically
            # platform-agnostic and more likely to include complete source-level license files.
            license_texts = _heuristic_sdist_license_texts(tf, root_dir)
        return license_name, license_texts


def _artifact_metadata_from_lockfile(pkg: dict[str, Any]) -> tuple[str, list[tuple[str, str]]]:
    """Read license metadata from the locked artifacts for one package.

    Prefer the sdist when available because it is less platform-specific than a
    wheel. Fall back to the first locked wheel only when the package has no sdist.
    """
    package_name = pkg["name"]
    sdist = pkg.get("sdist")
    if isinstance(sdist, dict) and sdist.get("url") and sdist.get("hash"):
        data = _download_locked_artifact(sdist["url"], sdist["hash"])
        return _sdist_metadata_from_bytes(data, package_name=package_name)

    wheels = cast(list[dict[str, Any]], pkg.get("wheels") or [])
    for wheel in wheels:
        if wheel.get("url") and wheel.get("hash"):
            data = _download_locked_artifact(wheel["url"], wheel["hash"])
            return _wheel_metadata_from_bytes(data, package_name=package_name)

    raise ValueError(f"No downloadable artifact found in uv.lock for {package_name}")


def _installed_python_packages(
    rows: list[dict[str, str]], lockfile_pkgs: dict[str, dict[str, Any]], *, own_name: str
) -> tuple[list[RenderedPythonPackage], set[str]]:
    """Render Python packages reported by pip-licenses and track which lockfile entries were seen."""
    packages: list[RenderedPythonPackage] = []
    seen: set[str] = set()

    for row in rows:
        name = row.get("Name", "unknown")
        normalized = _normalize_package_name(name)
        if normalized == own_name or normalized not in lockfile_pkgs:
            continue
        seen.add(normalized)
        lic = (row.get("License") or "UNKNOWN").strip() or "UNKNOWN"
        license_file = (row.get("LicenseFile") or "").strip()
        path_label = _pypi_license_path_display(license_file)
        text = "\n".join(line.rstrip() for line in (row.get("LicenseText") or "").splitlines()).strip()
        if not text:
            text = f"(No license text bundled in site-packages for {name}; see package metadata or PyPI.)\n"
        packages.append(
            RenderedPythonPackage(
                name=name,
                version=row.get("Version", ""),
                license_name=lic,
                license_texts=[(path_label, text)],
            )
        )

    return packages, seen


def _lockfile_fallback_license_texts(package_name: str) -> list[tuple[str, str]]:
    """Return a stable placeholder when no bundled license file can be resolved from the artifact."""
    return [
        ("LICENSE", f"(No license file found in locked artifact for {package_name}; see package metadata or PyPI.)\n")
    ]


def _lockfile_only_python_package(pkg: dict[str, Any]) -> RenderedPythonPackage:
    """Render one package that only appears in uv.lock and not in the current installed environment."""
    license_name, license_texts = _artifact_metadata_from_lockfile(pkg)
    if not license_texts:
        license_texts = _lockfile_fallback_license_texts(str(pkg["name"]))
    return RenderedPythonPackage(
        name=str(pkg["name"]),
        version=str(pkg["version"]),
        license_name=license_name,
        license_texts=license_texts,
    )


def _missing_lockfile_python_packages(
    lockfile_pkgs: dict[str, dict[str, Any]], seen: set[str], *, own_name: str
) -> list[RenderedPythonPackage]:
    """Render the remaining uv.lock packages that pip-licenses did not report."""
    packages: list[RenderedPythonPackage] = []
    for normalized, pkg in lockfile_pkgs.items():
        if normalized == own_name or normalized in seen:
            continue
        packages.append(_lockfile_only_python_package(pkg))
    return packages


def cmd_python() -> int:
    """Generate ATTRIBUTIONS-Python.md from the current locked install plus archive fallback."""
    out = ROOT / "ATTRIBUTIONS-Python.md"
    pip_licenses_bin = ROOT / ".venv" / "bin" / "pip-licenses"

    subprocess.run(["uv", "sync", "--locked"], cwd=ROOT, check=True)  # noqa: S607
    if not pip_licenses_bin.exists():
        raise FileNotFoundError(f"pip-licenses not found after sync: {pip_licenses_bin}")
    lockfile_pkgs = _lockfile_registry_packages()
    own_name = "nemo-flow"

    proc = subprocess.run(  # noqa: S603 - pip_licenses_bin is validated and comes from the local virtualenv.
        [str(pip_licenses_bin), "-f", "json", "-u", "-l"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    rows: list[dict[str, str]] = json.loads(proc.stdout)

    # First trust the current locked install: pip-licenses already knows how to
    # interpret installed dist-info metadata and bundled license files.
    packages, seen = _installed_python_packages(rows, lockfile_pkgs, own_name=own_name)

    # Then backfill only the lockfile packages that pip-licenses did not report.
    # This is common for packages skipped on the current platform or omitted by
    # pip-licenses itself even though they are present in uv.lock.
    packages.extend(_missing_lockfile_python_packages(lockfile_pkgs, seen, own_name=own_name))

    packages.sort(key=lambda r: (str(r["name"]).lower(), str(r["version"])))

    parts: list[str] = [PYTHON_HEADER]
    for pkg in packages:
        _render_python_package(
            parts,
            name=pkg["name"],
            version=pkg["version"],
            license_name=pkg["license_name"],
            license_texts=pkg["license_texts"],
        )

    out.write_text("".join(parts).rstrip("\n") + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}", file=sys.stderr)
    return 0


def cmd_node() -> int:
    """Generate ATTRIBUTIONS-Node.md from package-lock.json via license-checker."""
    out = ROOT / "ATTRIBUTIONS-Node.md"

    subprocess.run(["npm", "ci"], cwd=NODE, check=True)  # noqa: S607
    proc = subprocess.run(
        ["npx", "--yes", "license-checker@25.0.1", "--json"],  # noqa: S607
        cwd=NODE,
        capture_output=True,
        text=True,
        check=True,
    )
    data: dict[str, dict[str, str]] = json.loads(proc.stdout)
    keys = sorted(data.keys(), key=lambda k: k.lower())

    parts: list[str] = [NODE_HEADER]
    for key in keys:
        meta = data[key]
        idx = key.rfind("@")
        if idx <= 0:
            name, ver = key, ""
        else:
            name, ver = key[:idx], key[idx + 1 :]

        lic = meta.get("licenses") or "UNKNOWN"
        repo = (meta.get("repository") or "").strip()
        if not repo:
            repo = f"https://www.npmjs.com/package/{name}"
        lic_url = spdx_url(str(lic), fallback="https://opensource.org/licenses/")
        text = ""
        lf = meta.get("licenseFile")
        if lf:
            try:
                raw = Path(lf).read_text(encoding="utf-8", errors="replace").strip()
                text = "\n".join(line.rstrip() for line in raw.splitlines())
            except OSError:
                text = ""

        parts.append(f"## {name} - {ver}\n")
        parts.append(f"**Repository URL**: {repo}\n")
        parts.append(f"**License Type(s)**: {lic}\n")
        parts.append(f"### License: {lic_url}\n")
        parts.append("```\n")
        parts.append(text if text else f"(No license file read from node_modules for {name}; see npm metadata.)\n")
        parts.append("```\n\n")

    out.write_text("".join(parts).rstrip("\n") + "\n", encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}", file=sys.stderr)
    return 0


def main() -> int:
    """Dispatch the lockfile-to-markdown generator for the requested ecosystem."""
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("python", help="ATTRIBUTIONS-Python.md from uv.lock")
    sub.add_parser("node", help="ATTRIBUTIONS-Node.md from package-lock.json")
    args = p.parse_args()
    if args.cmd == "python":
        return cmd_python()
    if args.cmd == "node":
        return cmd_node()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
